set_property PACKAGE_PIN B23 [get_ports SPI_0_io0_io]
set_property PACKAGE_PIN A23 [get_ports SPI_0_io1_io]
set_property PACKAGE_PIN F25 [get_ports SPI_0_sck_io]
set_property PACKAGE_PIN E20 [get_ports SPI_0_ss_io]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_0_io0_io]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_0_io1_io]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_0_sck_io]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_0_ss_io]
set_property PACKAGE_PIN K24 [get_ports {GPIO_0_tri_io[0]}]
set_property PACKAGE_PIN L23 [get_ports {GPIO_0_tri_io[1]}]
set_property PACKAGE_PIN L22 [get_ports {GPIO_0_tri_io[2]}]
set_property PACKAGE_PIN D7 [get_ports {GPIO_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_tri_io[0]}]



set_property PACKAGE_PIN AP9 [get_ports {GPIO_0_tri_io[4]}]
set_property PACKAGE_PIN AP10 [get_ports {GPIO_0_tri_io[5]}]
set_property PACKAGE_PIN AP12 [get_ports {GPIO_0_tri_io[6]}]
set_property PACKAGE_PIN AN12 [get_ports {GPIO_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_1_io0_io]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_1_io1_io]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_1_sck_io]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_1_ss_io]
set_property PACKAGE_PIN AN8 [get_ports SPI_1_io0_io]
set_property PACKAGE_PIN AN9 [get_ports SPI_1_io1_io]
set_property PACKAGE_PIN AP11 [get_ports SPI_1_sck_io]
set_property PACKAGE_PIN AN11 [get_ports SPI_1_ss_io]
