# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jcoffman/work/zcu106_example/zcu106_example.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_xbar_0/Base_Zynq_MPSoC_xbar_0.xci
# IP: The module: 'Base_Zynq_MPSoC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jcoffman/work/zcu106_example/zcu106_example.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_xbar_0/Base_Zynq_MPSoC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jcoffman/work/zcu106_example/zcu106_example.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_xbar_0/Base_Zynq_MPSoC_xbar_0.xci
# IP: The module: 'Base_Zynq_MPSoC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jcoffman/work/zcu106_example/zcu106_example.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_xbar_0/Base_Zynq_MPSoC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
